baseURL = "https://recommandations-medicales.netlify.app/"
# canonifyURLs = false
# relativeURLs = true
copyright = "Tous droits réservés ©"
DefaultContentLanguage = "fr"
disableHugoGeneratorInject = false
enableInlineShortcodes = true
enableRobotsTXT = true
languageCode = "fr"
rssLimit = 20
summaryLength = 50
title = "L'Université médicale"

[permalinks]
  recommandations = "/recommandations/:filename/"

[taxonomies]
  category = "categories"
  tag = "tags"
  # auteur = "auteurs"
  guidelineyear = "guidelineyears"
  # source = "sources"

[params]
  author = "Jean-Baptiste FRON"
  dateFormat = "02/01/2006"
  description = "Site communautaire des recommandations en premier recours en médecine générale"
  github = "https://github.com/djibe/recommandations-medicales"
  githubUser = "djibe"
  og_image = "/images/icons/banner-og.png"
  SidebarRecentLimit = 5

# todo
[related.indices]
  name = "categories"

# search https://learn.netlify.app/en/basics/configuration/
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "JSON"]

# Dependencies
[params.cdn]
  material_css = "https://cdn.jsdelivr.net/gh/djibe/material@4.5.3-rc3/css/material.min.css"
  material_js = "https://cdn.jsdelivr.net/gh/djibe/material@4.5.3-rc3/js/material.min.js"
  css =         "css/style.css"
  bs_js =       "https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
  bs_js_hash =  "sha256-jXCJJT3KKcnNjZ3rfsabCj1EX4j2omR4xxm+H5CtywE="
  jquery =      "https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
  jquery_hash = "sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs="
  md_font =     "https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
  md_icons =    "https://fonts.googleapis.com/css2?family=Material+Icons+Outlined"

[params.dateformat]
# HTML doc : https://developer.mozilla.org/fr/docs/Web/HTML/Element/time
  #date = 2006-01-02
  #datetime = "2006-01-02T15:04:05Z0700"  # html ISO 8601 datetimeformat

[minify]

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "recommandations"
    name = "Recommandations"
    url = "/recommandations/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3