baseURL = "https://recommandations-medicales.netlify.app/"
# canonifyURLs = false
# relativeURLs = true
copyright = "Tous droits réservés ©"
DefaultContentLanguage = "fr"
disableHugoGeneratorInject = false
enableInlineShortcodes = true
enableRobotsTXT = true
languageCode = "fr"
rssLimit = 30
summaryLength = 50
title = "Recommandations Médicales"

[permalinks]
  recommandations = "/recommandations/:filename/"

[taxonomies]
  specialite = "specialites"
  tag = "tags"
  # auteur = "auteurs"
  annee = "annees"
  # source = "sources"

[params]
  author = "Jean-Baptiste FRON"
  dateFormat = "02/01/2006"
  description = "Les recommandations de référence pour la médecine générale"
  github = "https://github.com/djibe/recommandations-medicales"
  githubUser = "djibe"
  facebook = "https://www.facebook.com/RecoMedicales"
  ogimage = "/images/icons/banner-og.png"
  icon = "/android-chrome-192x192.png"
  SidebarRecentLimit = 5

# todo
[related.indices]
  name = "specialites"

# https://gohugo.io/templates/output-formats/#output-formats-for-pages
# search https://learn.netlify.app/en/basics/configuration/
[outputs]
  page = ["HTML"]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

# Dependencies
[params.cdn]
  material_js = "https://cdn.jsdelivr.net/npm/djibe-material@4.6.0-rc.2/js/material.min.js"
  css =         "css/style.css"
  bs_js =       "https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
  bs_js_hash =  "sha256-fgLAgv7fyCGopR/gBNq2iW3ZKIdqIcyshnUULC4vex8="
  jquery =      "https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"
  jquery_hash = "sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI="

[params.dateformat]
# HTML doc : https://developer.mozilla.org/fr/docs/Web/HTML/Element/time
  #date = 2006-01-02
  #datetime = "2006-01-02T15:04:05Z0700"  # html ISO 8601 datetimeformat

[minify.tdewolff.html]
  keepWhitespace = false

[markup.goldmark.parser.attribute]
  block = true # Allow classes on HTML entities
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "recommandations"
    name = "Recommandations"
    url = "/recommandations/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Mots-clés"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "projet"
    name = "Projet"
    url = "/projet/"
    weight = 4