[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.80.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.80.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "*.html*"
  [headers.values]
    Cache-Control = "public, max-age=1800, must-revalidate"

[[headers]]
  for = "*.json*"
  [headers.values]
    Cache-Control = "public, max-age=1800, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=1209600, must-revalidate" # 2 weeks ; 3M = 7257600

[[headers]]
  for = "*.jpg*"
  [headers.values]
    Cache-Control = "public, max-age=2419200, must-revalidate, stale-while-revalidate=86400"

[[headers]]
  for = "*.svg*"
  [headers.values]
    Cache-Control = "public, max-age=2419200, must-revalidate, stale-while-revalidate=86400"

[[redirects]]
  from = "/guidelineyears/*"
  to = " /annees/:splat"
  status = 301

[[redirects]]
  from = "/categories/*"
  to = " /specialites/:splat"
  status = 301