[Settings]
ID = "327af24a-1868-47c1-959c-7c0afe3b1891"

[build]
publish = "public"
command = "hugo --cleanDestinationDir --gc --minify"

[build.environment]
NODE_VERSION = "14.16"

[context.production.environment]
HUGO_VERSION = "0.98.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "false"

[context.split1]
command = "hugo --gc --minify"

[context.split1.environment]
HUGO_VERSION = "0.98.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.98.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.98.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "false"

[[headers]]
  for = "*.html*"
  [headers.values]
    Cache-Control = "private, max-age=1800"

[[headers]]
  for = "*.json*"
  [headers.values]
    Cache-Control = "public, max-age=1800, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=1209600, must-revalidate" # 2 weeks ; 3M = 7257600

[[headers]]
  for = "*.jpg*"
  [headers.values]
    Cache-Control = "public, max-age=2419200, must-revalidate, stale-while-revalidate=86400"

[[headers]]
  for = "*.svg*"
  [headers.values]
    Cache-Control = "public, max-age=2419200, must-revalidate, stale-while-revalidate=86400"

[[redirects]]
  from = "https://recommandations-medicales.netlify.app/*"
  to = "https://recomedicales.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.recomedicales.fr/*"
  to = "https://recomedicales.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.recomedicales.fr/*"
  to = "https://recomedicales.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://recomedicales.fr/*"
  to = "https://recomedicales.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/guidelineyears/*"
  to = " /annees/:splat"
  status = 301

[[redirects]]
  from = "/categories/*"
  to = " /specialites/:splat"
  status = 301

[[plugins]]
  package = "netlify-plugin-inline-critical-css"

  [plugins.inputs]
  directoryFilter = ["annees", "specialites", "tags"]
