[Settings]
ID = "327af24a-1868-47c1-959c-7c0afe3b1891"

[build]
publish = "public"
command = "hugo --cleanDestinationDir --gc --minify"

[build.environment]
NODE_VERSION = "16"

[context.production.environment]
HUGO_VERSION = "0.115.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "false"
NODE_ENV = "production"

[context.split1]
command = "hugo --gc --minify"

[context.split1.environment]
HUGO_VERSION = "0.115.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.115.2"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.115.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "false"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600" # 1h for analytics

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600" # 1h for analytics

[[headers]]
  for = "*.json"
  [headers.values]
    Cache-Control = "public, max-age=1209600, must-revalidate, stale-while-revalidate=86400" # 2w

[[headers]]
  for = "*.css*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js*"
  [headers.values]
    Cache-Control = "public, max-age=1209600" # 2w

[[headers]]
  for = "favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=14515200, must-revalidate" # 6m

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2419200, must-revalidate, stale-while-revalidate=86400"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2419200, must-revalidate, stale-while-revalidate=86400"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=2419200, must-revalidate, stale-while-revalidate=86400"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=2419200, must-revalidate, stale-while-revalidate=86400"

[[redirects]]
  from = "https://recommandations-medicales.netlify.app/*"
  to = "https://recomedicales.fr/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/images/photos/canal-carpien.webp"
  to = "/images/photos/syndrome-canal-carpien.webp"
  status = 301

[[redirects]]
  from = "/recommandations/contraception/céphalées"
  to = "/recommandations/contraception/"
  status = 301

[[redirects]]
  from = "/recommandations/contraception/tags/mvte/"
  to = "/recommandations/contraception/"
  status = 301

[[redirects]]
  from = "/recommandations/papillomavirus/"
  to = "/recommandations/cancer-col-uterus/"
  status = 301

[[redirects]]
  from = "/?ref="
  to = "https://recomedicales.fr/"
  status = 301

[[redirects]]
  from = "/recommandations/remboursement-psychologue-monpsy/"
  to = "/recommandations/remboursement-psychologue-monparcourspsy/"
  status = 301

# [[plugins]]
#   package = "netlify-plugin-inline-critical-css"
#     [plugins.inputs]
#       directoryFilter = ["!annees", "!specialites", "!tags"]
